# Generated by Django 5.1.7 on 2025-03-12 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_galleryimage_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=67)),
                ('price', models.IntegerField(max_length=59)),
            ],
        ),
        migrations.CreateModel(
            name='SubplanFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=67)),
                ('Subplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subplan')),
            ],
        ),
    ]
