# Generated by Django 5.1.7 on 2025-03-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_subplan_subplanfeatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='subplan',
            name='highlited',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='subplan',
            name='price',
            field=models.IntegerField(),
        ),
    ]
