# Generated by Django 5.1.7 on 2025-03-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_subplan_highlited_alter_subplan_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='time_tag',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='time_tag',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
